# -*- coding: utf-8 -*-
"""Aula 01 - Operadores, Atribuição, Comparação

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1BEva0aSRIpIWj9nlTu12KR7-6p6ull

**Operadores**
"""

x= (6+4*2)
print (x)

x= (4*9+5)
print (x)

x=((6+7)*9)
print (x)

x=(15+20-30)
print (x)

x=(6+5**2)
print (x)

"""**Atribuição**"""

x=8
print (x)

x+=5
print (x)

x-=4
print(x)

x*=20
print (x)

x/=2
print (x)

x=8
x+=5
x-=4
x*=20
x/=2
print (x)

""" **Operadores de Comparação**"""

x=8
print (x)

x = 1
x1 = 3

x_result = x < x1
print (x_result)

x = 1
x1 = 3

x_result = x == x1
print (x_result)

x = 1
x1 = 3

x_result = x >= x1
print (x_result)

x = 1
x1 = 3

x_result = x != x1
print (x_result)

"""**Operadores de Lógica**"""

idade_lucas = 21
idade_caroline = 19

idade = idade_lucas >=18 or idade_caroline >=18
print (idade)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

x_result = x1 is x3
print (x_result)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

x_result = x1 is not x2
print (x_result)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

x_result = x1 is x2
print (x_result)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

x_result = x2 is not x3
print (x_result)

"""**Operadores de Associação**"""

frutas = ["banana", "laranja", "uva", "ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "uva"
x4 = "abacaxi"

x_result = x1 in frutas
print (x_result)

frutas = ["banana", "laranja", "uva", "ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "uva"
x4 = "abacaxi"

x_result = x1 not in frutas
print (x_result)

frutas = ["banana", "laranja", "uva", "ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "uva"
x4 = "abacaxi"

x_result = x2 not in frutas
print (x_result)

frutas = ["banana", "laranja", "uva", "ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "uva"
x4 = "abacaxi"

x_result = x3 in frutas
print (x_result)